# Generated by Django 2.2.5 on 2020-07-28 12:34

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realmapping',
            name='geom',
            field=djgeojson.fields.PointField(default=dict),
        ),
    ]
