# Generated by Django 2.2.14 on 2020-07-30 14:29

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_realmapping_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realmapping',
            name='geom',
            field=djgeojson.fields.PointField(),
        ),
    ]
